"""
PDF Report Generator for Smart E-Learning Automator
Generates comprehensive learning progress reports
"""
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.pdfgen import canvas
from datetime import datetime
import os
from database import Database
from typing import Optional


class ReportGenerator:
    """Generate PDF reports for learning progress"""
    
    def __init__(self, user_id: int = None):
        self.user_id = user_id
        self.db = Database(user_id=user_id)
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles"""
        # Title style
        self.title_style = ParagraphStyle(
            'CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#667eea'),
            spaceAfter=30,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        )
        
        # Subtitle style
        self.subtitle_style = ParagraphStyle(
            'CustomSubtitle',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#764ba2'),
            spaceAfter=12,
            alignment=TA_LEFT,
            fontName='Helvetica-Bold'
        )
        
        # Normal style
        self.normal_style = ParagraphStyle(
            'CustomNormal',
            parent=self.styles['Normal'],
            fontSize=11,
            spaceAfter=12,
            alignment=TA_LEFT
        )
        
        # Footer style
        self.footer_style = ParagraphStyle(
            'Footer',
            parent=self.styles['Normal'],
            fontSize=9,
            textColor=colors.grey,
            alignment=TA_CENTER
        )
    
    def generate_report(self, output_path: str = None, username: str = "User") -> str:
        """
        Generate comprehensive PDF report
        
        Args:
            output_path: Path to save PDF (default: data/reports/)
            username: User's name for the report
            
        Returns:
            Path to generated PDF file
        """
        # Setup output path
        if output_path is None:
            reports_dir = os.path.join(os.path.dirname(__file__), '..', 'data', 'reports')
            os.makedirs(reports_dir, exist_ok=True)
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            user_suffix = f"_user{self.user_id}" if self.user_id else ""
            output_path = os.path.join(reports_dir, f'learning_report{user_suffix}_{timestamp}.pdf')
        
        # Create PDF document
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=18
        )
        
        # Container for PDF elements
        elements = []
        
        # Add title
        title = Paragraph(
            f"📚 Learning Progress Report",
            self.title_style
        )
        elements.append(title)
        elements.append(Spacer(1, 12))
        
        # Add user info and date
        user_info = Paragraph(
            f"<b>Student:</b> {username}<br/>"
            f"<b>Report Generated:</b> {datetime.now().strftime('%B %d, %Y at %I:%M %p')}<br/>"
            f"<b>User ID:</b> {self.user_id if self.user_id else 'N/A'}",
            self.normal_style
        )
        elements.append(user_info)
        elements.append(Spacer(1, 20))
        
        # Add summary statistics
        elements.append(self._create_summary_section())
        elements.append(Spacer(1, 20))
        
        # Add completed videos section
        elements.append(self._create_videos_section())
        elements.append(Spacer(1, 20))
        
        # Add playlist progress section
        elements.append(self._create_playlist_section())
        elements.append(Spacer(1, 20))
        
        # Add quiz performance section
        elements.append(self._create_quiz_section())
        elements.append(Spacer(1, 20))
        
        # Add activity logs section
        elements.append(self._create_activity_section())
        
        # Add footer
        elements.append(Spacer(1, 30))
        footer = Paragraph(
            "Generated by Smart E-Learning Automator | Keep Learning! 🚀",
            self.footer_style
        )
        elements.append(footer)
        
        # Build PDF
        doc.build(elements)
        
        return output_path
    
    def _create_summary_section(self):
        """Create summary statistics section"""
        subtitle = Paragraph("📊 Summary Statistics", self.subtitle_style)
        
        # Get statistics with safe defaults
        completed_videos = self.db.get_completed_videos() or []
        quiz_stats = self.db.get_quiz_stats() or {'total_attempts': 0, 'correct_answers': 0, 'wrong_answers': 0, 'accuracy': 0, 'avg_confidence': 0}
        playlists = self.db.get_playlist_progress() or []
        
        total_videos = len(completed_videos)
        total_playlists = len(playlists)
        total_playlist_videos = sum([p.get('total_videos_watched', 0) for p in playlists])
        quiz_accuracy = quiz_stats.get('accuracy', 0)
        total_quizzes = quiz_stats.get('total_attempts', 0)
        
        # Create table
        data = [
            ['Metric', 'Value'],
            ['Total Videos Completed', str(total_videos)],
            ['Total Playlists Started', str(total_playlists)],
            ['Playlist Videos Watched', str(total_playlist_videos)],
            ['Quiz Attempts', str(total_quizzes)],
            ['Quiz Accuracy', f"{quiz_accuracy:.1f}%"],
        ]
        
        table = Table(data, colWidths=[3.5*inch, 2*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#667eea')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('TEXTCOLOR', (0, 1), (-1, -1), colors.black),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
        ]))
        
        return [subtitle, table]
    
    def _create_videos_section(self):
        """Create completed videos section"""
        subtitle = Paragraph("🎥 Recently Completed Videos (Last 15)", self.subtitle_style)
        
        completed_videos = self.db.get_completed_videos() or []
        
        if not completed_videos:
            no_data = Paragraph("No videos completed yet.", self.normal_style)
            return [subtitle, no_data]
        
        # Create table
        data = [['#', 'Title', 'Platform', 'Date']]
        
        for idx, video in enumerate(completed_videos[:15], 1):
            title = video.get('title', 'Unknown')[:50]  # Truncate long titles
            platform = video.get('platform', 'N/A').upper()
            watched_at = video.get('watched_at', 'N/A')
            
            # Format date
            if watched_at and watched_at != 'N/A':
                try:
                    date_obj = datetime.fromisoformat(watched_at)
                    watched_at = date_obj.strftime('%Y-%m-%d')
                except:
                    pass
            
            data.append([str(idx), title, platform, watched_at])
        
        table = Table(data, colWidths=[0.4*inch, 3.2*inch, 0.9*inch, 1*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#764ba2')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
        ]))
        
        return [subtitle, table]
    
    def _create_playlist_section(self):
        """Create playlist progress section"""
        subtitle = Paragraph("📺 Playlist Progress", self.subtitle_style)
        
        playlists = self.db.get_playlist_progress() or []
        
        if not playlists:
            no_data = Paragraph("No playlists tracked yet.", self.normal_style)
            return [subtitle, no_data]
        
        # Create table
        data = [['#', 'Playlist URL', 'Videos Watched', 'Last Updated']]
        
        for idx, playlist in enumerate(playlists[:10], 1):
            url = playlist.get('playlist_url', 'Unknown')[:50] + "..."  # Truncate URL
            videos = str(playlist.get('total_videos_watched', 0))
            updated = playlist.get('last_updated', 'N/A')
            
            # Format date
            if updated and updated != 'N/A':
                try:
                    date_obj = datetime.fromisoformat(updated)
                    updated = date_obj.strftime('%Y-%m-%d')
                except:
                    pass
            
            data.append([str(idx), url, videos, updated])
        
        table = Table(data, colWidths=[0.4*inch, 3*inch, 1.2*inch, 1*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#667eea')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
        ]))
        
        return [subtitle, table]
    
    def _create_quiz_section(self):
        """Create quiz performance section"""
        subtitle = Paragraph("📝 Quiz Performance", self.subtitle_style)
        
        quiz_stats = self.db.get_quiz_stats() or {'total_attempts': 0, 'correct_answers': 0, 'wrong_answers': 0, 'accuracy': 0, 'avg_confidence': 0}
        
        # Create summary paragraph
        summary = Paragraph(
            f"<b>Total Attempts:</b> {quiz_stats.get('total_attempts', 0)}<br/>"
            f"<b>Correct Answers:</b> {quiz_stats.get('correct_answers', 0)}<br/>"
            f"<b>Wrong Answers:</b> {quiz_stats.get('wrong_answers', 0)}<br/>"
            f"<b>Accuracy:</b> {quiz_stats.get('accuracy', 0):.1f}%<br/>"
            f"<b>Average Confidence:</b> {quiz_stats.get('avg_confidence', 0):.1f}%",
            self.normal_style
        )
        
        return [subtitle, summary]
    
    def _create_activity_section(self):
        """Create activity logs section"""
        subtitle = Paragraph("📋 Recent Activity (Last 10)", self.subtitle_style)
        
        logs = self.db.get_recent_logs(limit=10) or []
        
        if not logs:
            no_data = Paragraph("No activity logs available.", self.normal_style)
            return [subtitle, no_data]
        
        # Create table
        data = [['Date/Time', 'Action', 'Details', 'Status']]
        
        for log in logs:
            timestamp = log.get('timestamp', 'N/A')
            
            # Format timestamp
            if timestamp and timestamp != 'N/A':
                try:
                    date_obj = datetime.fromisoformat(timestamp)
                    timestamp = date_obj.strftime('%m/%d %H:%M')
                except:
                    pass
            
            action = log.get('action', 'N/A')
            details = log.get('details', '')[:30]  # Truncate
            status = log.get('status', 'N/A').upper()
            
            data.append([timestamp, action, details, status])
        
        table = Table(data, colWidths=[1*inch, 1.2*inch, 2.4*inch, 0.9*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#764ba2')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
        ]))
        
        return [subtitle, table]


def generate_user_report(user_id: int = None, username: str = "User") -> str:
    """
    Convenience function to generate report
    
    Args:
        user_id: User ID for user-specific report
        username: User's name
        
    Returns:
        Path to generated PDF
    """
    generator = ReportGenerator(user_id=user_id)
    return generator.generate_report(username=username)


if __name__ == "__main__":
    # Test report generation
    report_path = generate_user_report(username="Test User")
    print(f"Report generated: {report_path}")
